# Generated by Django 5.0.1 on 2024-02-10 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatWithCounsellors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counsellor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_portal.counsellor')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_portal.acu')),
            ],
        ),
    ]
