# Generated by Django 5.0.1 on 2024-02-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career_portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
