# Generated by Django 5.0.1 on 2024-02-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0002_remove_acu_confirmpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='name',
            new_name='qualification',
        ),
        migrations.RemoveField(
            model_name='counsellor',
            name='field_of_study',
        ),
        migrations.AddField(
            model_name='qualification',
            name='field_of_study',
            field=models.TextField(null=True),
        ),
    ]
