# Generated by Django 5.0.1 on 2024-02-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0003_rename_name_qualification_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='field_of_study',
            field=models.TextField(),
        ),
    ]
