# Generated by Django 5.0.1 on 2024-02-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0004_alter_qualification_field_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingexperience',
            name='ending_date',
        ),
        migrations.RemoveField(
            model_name='workingexperience',
            name='starting_date',
        ),
        migrations.AddField(
            model_name='workingexperience',
            name='ending_year',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workingexperience',
            name='starting_year',
            field=models.TextField(null=True),
        ),
    ]
