# Generated by Django 5.0.1 on 2024-02-01 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0004_alter_qualification_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='counsellor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='career_portal.counsellor'),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='counsellor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counsellors', to='career_portal.acu'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='counsellor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='qualification', serialize=False, to='career_portal.counsellor'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='counsellor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='career_portal.counsellor'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='career_portal.acu'),
        ),
        migrations.AlterField(
            model_name='workingexperience',
            name='counsellor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_experiences', to='career_portal.counsellor'),
        ),
        migrations.AlterField(
            model_name='workingexperience',
            name='ending_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workingexperience',
            name='starting_date',
            field=models.TextField(),
        ),
    ]
