# Generated by Django 5.0.1 on 2024-02-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0005_remove_workingexperience_ending_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingexperience',
            name='ending_year',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workingexperience',
            name='starting_year',
            field=models.TextField(),
        ),
    ]
