# Generated by Django 5.0.1 on 2024-02-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0005_alter_blogs_counsellor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='profile_pic',
            field=models.TextField(default='jj'),
        ),
    ]
