# Generated by Django 5.0.1 on 2024-02-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0006_alter_workingexperience_ending_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='profile_pic',
            field=models.TextField(null=True),
        ),
    ]
