# Generated by Django 5.0.1 on 2024-02-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0007_alter_counsellor_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='reviewer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
