# Generated by Django 5.0.1 on 2024-02-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0010_remove_counsellor_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='profile_pic',
            field=models.TextField(null=True),
        ),
    ]
